### ISSUE TITLE
Provide a winner column total score at the bottom

### ISSUE THREAD

**Issue by mcmxcdev** [jasongitmail/svelte-vs-next#3]
Amazing comparison table! I was wondering today if SvelteKit would ever have the chance to become more popular than Next.js and found your repo after a quick search. It seems it is definitely possible since SvelteKit is up to par or even more feature-complete in the aspects listed.

It would be great to have a winner total at the bottom, e.g. SvelteKit 30/35 categories vs Next 25/35 categories to get a fast summary.

Also, https://github.com/matyunya/svelte-image that you have linked, is not maintained well and didn't seem to work with SvelteKit (from what I tried). People seem to use https://github.com/JonasKruckenberg/imagetools instead, until https://github.com/sveltejs/kit/issues/241 will be realized.

**Comment by lunacd** [comment]
> It would be great to have a winner total at the bottom, e.g. SvelteKit 30/35 categories vs Next 25/35 categories to get a fast summary.

I'm low-key not much of a fan of that because this page's users should look for things that are relevant to their specific use case. Providing an aggregate discourages such case-specific review of the page.

> Also, https://github.com/matyunya/svelte-image that you have linked, is not maintained well and didn't seem to work with SvelteKit (from what I tried). People seem to use https://github.com/JonasKruckenberg/imagetools instead, until https://github.com/sveltejs/kit/issues/241 will be realized.

Same experience. `vite-image-tools` should be the only one listed.

**Comment by mcmxcdev** [comment]
> I'm low-key not much of a fan of that because this page's users should look for things that are relevant to their specific use case. Providing an aggregate discourages such case-specific review of the page.

Fair enough!

> Same experience. vite-image-tools should be the only one listed.

I actually found https://github.com/xiphux/svimg to be the perfect replacement and have used it now on every project of mine.

**Comment by lunacd** [comment]
> I actually found https://github.com/xiphux/svimg to be the perfect replacement and have used it now on every project of mine.

Interesting! I'm more or less stuck with `vite-image-tools` for the time and will definitely take a look.

**Comment by jasongitmail** [comment]
> I'm low-key not much of a fan of that because this page's users should look for things that are relevant to their specific use case. Providing an aggregate discourages such case-specific review of the page.
> 
> > Fair enough!

Agree. I want to avoid inflaming any community. Just wanted a list to help me keep track of features for each frameworks. 

Thanks for the image suggestions. I've updated it with `svimg`, `vite-imagetools`, and link to official support issue thread.
