### ISSUE TITLE
svelte-query moved to TanStack/query

### ISSUE THREAD

**Issue by EcksDy** [jasongitmail/svelte-vs-next#7]
Hello,
thank you for the comparison, it's a very useful rundown of features.

I've noticed that `svelte-query` last release was almost a year ago.
Following the issue trail, it seems that [TanStack/query](https://github.com/TanStack/query), takes over maintenance.

Trail:
https://github.com/SvelteStack/svelte-query/issues/96#issuecomment-1288157511
https://github.com/TanStack/query/pull/4344#issuecomment-1374444973
https://github.com/TanStack/query/pull/4768

**Comment by jasongitmail** [comment]
Thanks! I updated the link to https://github.com/TanStack/query
